/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import ImagePanel.imageCarte;
import com.sun.media.jfxmediaimpl.NativeMediaPlayer;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.util.Vector;
import javafx.scene.layout.Border;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.border.MatteBorder;
import partie.partie;
import terrain.tuiles;

/**
 *
 * @author Takazeuk
 */
public class carteEnMain extends javax.swing.JFrame {
    BufferedImage m;
    partie partieEnCours;
    imageCarte[] tableauImage;
    JTextArea[] tableauTexte;
    JButton[] tableauBouton;
    /**
     * Creates new form carteEnMain
     */
    public carteEnMain(partie p) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        partieEnCours=p;
        tableauImage = new imageCarte[4];
        tableauTexte = new JTextArea[]{descriptionCarte1,descriptionCarte2,descriptionCarte3,descriptionCarte4};
        tableauBouton = new JButton[]{valideCarte1,valideCarte2,valideCarte3,valideCarte4};
        
        //je permet au zone de texte d'aller à la ligne
        for (JTextArea description : tableauTexte) {
            description.setLineWrap(true);
        }      
    }
    
    
    
    public void placementTuile()
    {
        int i = 0;
        for (tuiles carteMain : partieEnCours.participant.get(partieEnCours.tourJoueur).cartesEnMain) {
            //tableauImage[i]= carteMain.type;
            tableauTexte[i].setText(carteMain.descriptionPouvoir);
            imageCarte nouveau = new imageCarte(partieEnCours.participant.get(partieEnCours.tourJoueur).cartesEnMain.get(i));
            tableauImage[i]= nouveau;
            if(i==0)
            {
                Carte1.add(nouveau);
            }
            else if(i==1)
            {
                Carte2.add(nouveau);
            }
            else if(i==2)
            {
                Carte3.add(nouveau);
            }
            else
            {
                Carte4.add(nouveau);
            }
            nouveau.setBounds(5, 5, 187, 129);
            nouveau.setVisible(true);
            
            i++;
        }        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Carte1 = new javax.swing.JPanel();
        valideCarte1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionCarte1 = new javax.swing.JTextArea();
        Carte2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        descriptionCarte2 = new javax.swing.JTextArea();
        valideCarte2 = new javax.swing.JButton();
        Carte3 = new javax.swing.JPanel();
        valideCarte3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionCarte3 = new javax.swing.JTextArea();
        Carte4 = new javax.swing.JPanel();
        valideCarte4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        descriptionCarte4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Carte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        valideCarte1.setText("Valider");
        valideCarte1.setName("0"); // NOI18N
        valideCarte1.setOpaque(false);
        valideCarte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valideCarteActionPerformed(evt);
            }
        });

        descriptionCarte1.setEditable(false);
        descriptionCarte1.setColumns(20);
        descriptionCarte1.setRows(5);
        jScrollPane1.setViewportView(descriptionCarte1);

        javax.swing.GroupLayout Carte1Layout = new javax.swing.GroupLayout(Carte1);
        Carte1.setLayout(Carte1Layout);
        Carte1Layout.setHorizontalGroup(
            Carte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Carte1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Carte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valideCarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Carte1Layout.setVerticalGroup(
            Carte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Carte1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valideCarte1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Carte2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        descriptionCarte2.setEditable(false);
        descriptionCarte2.setColumns(20);
        descriptionCarte2.setRows(5);
        jScrollPane5.setViewportView(descriptionCarte2);

        valideCarte2.setText("Valider");
        valideCarte2.setName("0"); // NOI18N
        valideCarte2.setOpaque(false);
        valideCarte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valideCarteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Carte2Layout = new javax.swing.GroupLayout(Carte2);
        Carte2.setLayout(Carte2Layout);
        Carte2Layout.setHorizontalGroup(
            Carte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Carte2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(valideCarte2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Carte2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Carte2Layout.setVerticalGroup(
            Carte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Carte2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valideCarte2)
                .addContainerGap())
        );

        Carte3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        valideCarte3.setText("Valider");
        valideCarte3.setName("0"); // NOI18N
        valideCarte3.setOpaque(false);
        valideCarte3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valideCarteActionPerformed(evt);
            }
        });

        descriptionCarte3.setEditable(false);
        descriptionCarte3.setColumns(20);
        descriptionCarte3.setRows(5);
        jScrollPane3.setViewportView(descriptionCarte3);

        javax.swing.GroupLayout Carte3Layout = new javax.swing.GroupLayout(Carte3);
        Carte3.setLayout(Carte3Layout);
        Carte3Layout.setHorizontalGroup(
            Carte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Carte3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(Carte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valideCarte3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        Carte3Layout.setVerticalGroup(
            Carte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Carte3Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valideCarte3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Carte4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        valideCarte4.setText("Valider");
        valideCarte4.setName("0"); // NOI18N
        valideCarte4.setOpaque(false);
        valideCarte4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valideCarteActionPerformed(evt);
            }
        });

        descriptionCarte4.setEditable(false);
        descriptionCarte4.setColumns(20);
        descriptionCarte4.setRows(5);
        jScrollPane4.setViewportView(descriptionCarte4);

        javax.swing.GroupLayout Carte4Layout = new javax.swing.GroupLayout(Carte4);
        Carte4.setLayout(Carte4Layout);
        Carte4Layout.setHorizontalGroup(
            Carte4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Carte4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(valideCarte4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Carte4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Carte4Layout.setVerticalGroup(
            Carte4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Carte4Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valideCarte4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Carte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Carte3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carte4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Carte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Carte2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carte3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carte4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valideCarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valideCarteActionPerformed
        JButton sender = (JButton) evt.getSource();
        tuiles choisi;
        int choix = 0;
        int carte = 0;
        for (JButton boutonCarte : tableauBouton) {
            if (boutonCarte == sender) {
                carte = choix;
                choisi = partieEnCours.participant.get(partieEnCours.tourJoueur).cartesEnMain.get(carte);
                MessageBox.Interaction.messageJoueur(""+choisi.pouvoir);
                partieEnCours.pouvoirEnMainActiver(partieEnCours.participant.get(partieEnCours.tourJoueur), choisi);
            }
            choix ++;
        }
        partieEnCours.participant.get(partieEnCours.tourJoueur).cartesEnMain.remove(carte);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_valideCarteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carteEnMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carteEnMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carteEnMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carteEnMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //paffichageCarte();

    }
    
    public void affichageCarte(){
        /*for (tuiles carte : partieEnCours.participant.get(partieEnCours.tourJoueur).cartesEnMain) {
            this.jList1.add(new JButton("toto"));
        }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Carte1;
    private javax.swing.JPanel Carte2;
    private javax.swing.JPanel Carte3;
    private javax.swing.JPanel Carte4;
    private javax.swing.JTextArea descriptionCarte1;
    private javax.swing.JTextArea descriptionCarte2;
    private javax.swing.JTextArea descriptionCarte3;
    private javax.swing.JTextArea descriptionCarte4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton valideCarte1;
    private javax.swing.JButton valideCarte2;
    private javax.swing.JButton valideCarte3;
    private javax.swing.JButton valideCarte4;
    // End of variables declaration//GEN-END:variables
}
